---
environment_config:
  ORBBA_MEDIA_ENVIRONMENT: integrated
  ORBBA_MEDIA_LOG_LEVEL: debug
  ORBBA_MEDIA_RELAY_ADDRESS: localhost
  ORBBA_MEDIA_RELAY_PORT: 3478
  ORBBA_MEDIA_RELAY_REALM: orbba.tk
  ORBBA_MEDIA_SIGNALING_ADDRESS: localhost
  ORBBA_MEDIA_SIGNALING_PORT: 8090
  ORBBA_MEDIA_LOGGLY_API_KEY: "{{ loggly_api_key }}"
  ORBBA_MEDIA_LOGGLY_TAG: media

